# ***Project Title :** Play Store App Demographics and Technology- Category Adoption and User Base*
---
# ***Domain:** App-Store Analytics and Technology*

## Project Overview:
*- This project mainly focuses on performing an exploratory data analysis (EDA) and market evaluation of mobile applications sourced from the Google Play Store.  By examining a robust sample of over 100,000 apps, the project aims to uncover insights into how developers distribute their applications,how users reacting the technologies, how users adopt different genres, and how various attributes—such as monetization strategies, content ratings,evaluating games proportion,analysing free and paid applications,examinig user feedbacks and also ratings and technical specs—influence an application's market standing.*
                     *Situation it addresses: The mobile application market is a hyper-competitive ecosystem. Developers, product managers, and analysts frequently face the challenge of navigating market fluctuation, finding out which genres offer high demand, and understanding how secondary features (like ads and in-app purchases) affect overall user engagement.*

## Business Problem:
_- Understanding what users truly want in today's crowded app market is a complex challenge.The Diffrent stages of analysis will help to idnetify the users intrests and which type of genre they mostly intrested, the current trendline, the engagement ratio and the user reviews and rating are the key elements and those are the challenging phases needed proper decision to overcome all the problems.Addressing these challenges is essential for uncovering actionable insights, helping developers and stakeholders make informed decisions to optimize app performance and user satisfaction._

## Project Objectives:
   -    *Which application genres dominates the market in terms of volume and downloads?*
      -  Find the top 3 application genres using groupby in terms of average of installs
   -    *What patterns exist between user engagement metrics?*
      -  comparison of reviews,ratings,score and content ratings.
   -    *Which developer build the most successfull app by user engagement?*
      -  finding the top installs by developerwise using installs and user engagement parameters.
   -    *What was the actual proportion of mobile games compared to others in the data?*
      -  Know the proportion in is_game.
   -    *How do monitization strategies varys across the genres?*
      -  Findout the free and paid applocations and ads on the application.

## Business Value & Use Case:
*- Who benifits-App developers,product managers and market reserchers are looking to launch and optimize mobile products with new innovations. By providing clear insights using the current market data trends like analysing top moving ,user raings,user reviews and high user engagement applications also help the stakeholders to identify the market unwanted parameters and align the software update cycles with real market demand.The decision is much more effective when insights from deeper analysis.*

## Dataset Information:
#### *Source URL:https://www.kaggle.com/code/fliarbi/google-play-apps-2026-starter/input?select=google_play_apps_2026_sample.csv*

#### *Origin:Google Play Store application dataset sample.*

#### *Format:(.CSV)*

#### *Dimensions- 100,013 rows and 19 columns.*

### *Key Fields:*

#### *Identifiers & Metadata- app_id, title, developer, genre*

#### *Market Scale & Adoption- installs, released, last_updated*

#### *Engagement- score, ratings, reviews*

#### *Monetization & Technical- free, price, contains_ads, offers_iap, content_rating*

##### *What One Record Represents: A single mobile application available on the Google Play Store, detailing its public usage information, structural metadata, monetization model and genrewise application publishers.*

## Planned Analysis:
#### *Data Cleaning & Preprocessing:*
*- Inspect data types and handle missing values (notably in performance metrics like score and ratings for newer or niche apps, as well as released and developer_domain).Standardize categorical text fields and ensure proper boolean/numerical formatting.*

#### *Exploratory Data Analysis (EDA):*
*- Calculate summary statistics and finding the correlation for numerical variables (price, score, ratings) and frequency distributions for categorical fields (genre, content_rating).
Evaluate the distribution of free vs. paid apps and the prevalence of ad-supported and in-app purchase models.*

#### *Metrics & Charts:*
-  Top genres by top installs.
-  Game vs Non game proportion.
-  Distribution of average ratings across major categories using histogram and boxplots.
-  Average score by each developer

## Scope & Limitations:
#### Included:
*- The listings in this single file and the 19 available fields, analyzed descriptively.*

#### Excluded:
*- Revenue, downloads over time, user demographics, review text, rankings, and anything outside the file.*

#### Assumptions:
*-  Each row represents a distinct, currently listed app.*
*-  Install ranges and scores are accurate as scraped.*

#### Known constraints:
*The file name says “sample,” so I can’t assume the data represents the full Play Store. Conclusions apply to this sample.
Installs are bucketed ranges, not exact counts, which limits precision.
Scores from apps with very few ratings are unreliable, so I’ll set minimum thresholds.
The data is a single snapshot, so it can’t show how an app changes over time.
Correlations won’t prove that, for example, ads cause lower ratings.*

In [2]:
import pandas as pd
apps=pd.read_csv(r"C:\Users\indra\Downloads\google_play_apps_2026_sample (2).csv")

In [3]:
apps

,app_id,title,developer,developer_domain,genre,is_game,installs,score,ratings,reviews,free,price,currency,contains_ads,offers_iap,content_rating,released,last_updated,fliar_profile_url
0,com.facebook.katana,Facebook,"Meta Platforms, Inc.",facebook.com,Social,False,"10,000,000,000+",4.56,182075532.0,4251426.0,True,0.0,USD,True,True,Teen,NaN,2026-06-03,https://fliarbi.com/company/facebook/1dxlnk4j2...
1,com.facebook.orca,Messenger,"Meta Platforms, Inc.",facebook.com,Communication,False,"5,000,000,000+",4.72,112112364.0,2463383.0,True,0.0,USD,False,True,Everyone,2014-01-30,2026-06-01,https://fliarbi.com/company/facebook/1dxlnk4j2...
2,com.facebook.lite,Facebook Lite,"Meta Platforms, Inc.",facebook.com,Social,False,"1,000,000,000+",4.52,37191569.0,136089.0,True,0.0,USD,True,True,Teen,2018-03-15,2026-06-02,https://fliarbi.com/company/facebook/1dxlnk4j2...
3,com.twitter.android,X,X Corp.,twitter.com,News & Magazines,False,"1,000,000,000+",3.62,22991633.0,786522.0,True,0.0,USD,True,True,Mature 17+,2010-04-30,2026-06-05,https://fliarbi.com/company/fabula/k7j9a78ffq/...
4,flipboard.boxer.app,Briefing,Flipboard,flipboard.com,News & Magazines,False,"1,000,000,000+",3.15,751558.0,42003.0,True,0.0,USD,True,False,Teen,2015-05-13,2026-03-09,https://fliarbi.com/company/flipboard/2x8224kv...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100008,zeroinfinity.space.hindifunnyjokes,Hindi Mazedar Funny Jokes,Zeroinfinity Tech,zeroinfinity.space,Entertainment,False,"1,000+",NaN,NaN,NaN,True,0.0,USD,True,False,Everyone,2020-12-20,2025-04-16,NaN
100009,zip.gigantino.autem,Autem,Gigantino,autem.app,Productivity,False,"1,000+",NaN,NaN,NaN,True,0.0,USD,True,False,Everyone,NaN,2025-03-09,NaN
100010,zm.unza.unzastudentapp,UNZA Student,UNZA-CICT,unza.zm,Education,False,"1,000+",NaN,NaN,NaN,True,0.0,USD,False,False,Everyone,2025-12-01,2025-12-01,NaN
100011,zoo.ticket.eticket,จองตั๋วสวนสัตว์ Zoo E-ticket,"Addpay Service Point Co.,Ltd.",addpay.co.th,Shopping,False,"1,000+",NaN,NaN,NaN,True,0.0,USD,False,False,Everyone,2024-06-13,2026-05-10,NaN
100012,zundel.ag.letters,Notes,Arnon Tech,NaN,Productivity,False,"1,000+",NaN,NaN,NaN,True,0.0,USD,False,False,Everyone,2024-11-10,2024-12-07,NaN

In [4]:
apps.duplicated().sum()
# no duplicates rows in the dataset

np.int64(0)

In [5]:
apps.shape
# This dataset having 100013 instincts and 19 distinct features

(100013, 19)

In [6]:
apps.head()

,app_id,title,developer,developer_domain,genre,is_game,installs,score,ratings,reviews,free,price,currency,contains_ads,offers_iap,content_rating,released,last_updated,fliar_profile_url
0,com.facebook.katana,Facebook,"Meta Platforms, Inc.",facebook.com,Social,False,"10,000,000,000+",4.56,182075532.0,4251426.0,True,0.0,USD,True,True,Teen,NaN,2026-06-03,https://fliarbi.com/company/facebook/1dxlnk4j2...
1,com.facebook.orca,Messenger,"Meta Platforms, Inc.",facebook.com,Communication,False,"5,000,000,000+",4.72,112112364.0,2463383.0,True,0.0,USD,False,True,Everyone,2014-01-30,2026-06-01,https://fliarbi.com/company/facebook/1dxlnk4j2...
2,com.facebook.lite,Facebook Lite,"Meta Platforms, Inc.",facebook.com,Social,False,"1,000,000,000+",4.52,37191569.0,136089.0,True,0.0,USD,True,True,Teen,2018-03-15,2026-06-02,https://fliarbi.com/company/facebook/1dxlnk4j2...
3,com.twitter.android,X,X Corp.,twitter.com,News & Magazines,False,"1,000,000,000+",3.62,22991633.0,786522.0,True,0.0,USD,True,True,Mature 17+,2010-04-30,2026-06-05,https://fliarbi.com/company/fabula/k7j9a78ffq/...
4,flipboard.boxer.app,Briefing,Flipboard,flipboard.com,News & Magazines,False,"1,000,000,000+",3.15,751558.0,42003.0,True,0.0,USD,True,False,Teen,2015-05-13,2026-03-09,https://fliarbi.com/company/flipboard/2x8224kv...

In [7]:
apps.info()

<class 'pandas.DataFrame'>
RangeIndex: 100013 entries, 0 to 100012
Data columns (total 19 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   app_id             100013 non-null  str
 1   title              100013 non-null  str
 2   developer          100013 non-null  str
 3   developer_domain   63527 non-null   str
 4   genre              100013 non-null  str
 5   is_game            100013 non-null  bool
 6   installs           100013 non-null  str
 7   score              31755 non-null   float64
 8   ratings            31755 non-null   float64
 9   reviews            31755 non-null   float64
 10  free               100013 non-null  bool
 11  price              100000 non-null  float64
 12  currency           100013 non-null  str
 13  contains_ads       100013 non-null  bool
 14  offers_iap         100013 non-null  bool
 15  content_rating     100013 non-null  str
 16  released           82546 non-null   str
 17  last_updated       100013 non-null  str
 18  fliar_profile_url  30375 non-null   str
dtypes: bool(4), float64(4), str(11)
memory usage: 26.6 MB

## dataset having 11 str columns,4 bool columns,4 float columns that contains missing values also.Score,ratings,reviews having 31755 non null entries,meaning 68% is null.
## developer_domain, released, fliar_profile_url): Also show varying degrees of missing data, which you must account for during cleaning and preprocessing.